# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: linux-agent
  vmImage: linux-agent

variables:
  dockerImageTag: '$(Build.BuildId)'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'myhubpassword'
    repository: 'myrepo'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: '$(dockerImageTag)'